.TH KAREL 1 "Choate Rosemary Hall"
.UC 4
.SH NAME
karel \- interpreter for Karel's programming language
.SH SYNOPSIS
.br
.B karel
[
.B \-n
]
[
.B \-b
beepers
]
file.k
.br
.SH DESCRIPTION
.I Karel
is an interpreter for Karel's programming language, an introductory language
based on the structure of Pascal, which incorporates some of the visual
feedback possible from languages like Logo.
.PP
After reading the specified program (with a name ending in ".k"), a
screen with a corresponding name (ending in ".scr") is read if it exists. 
The screen editor is then called; from there, you can place Karel, the
robot, on the screen, and then run the program by pressing the return key.
.PP
The following flags are recognized by
.I karel:
.TP 8
.B \-b
Sets the number of beepers Karel will be holding at the start of program
execution (default is zero).
.br
.TP 8
.B \-n
Suppress loading of screen file
.br
.TP 0
.nf
The following is a list of the screen editor commands:

i       move cursor north (up)
j                   west (left)
k                   east (right)
m                   south (down)

I       place Karel facing north
J                          west
K                          east
M                          south

o       place wall section
q       quit; end execution of karel
s       save screen as file with suffix '.scr'
S       save picture of screen with borders, saved as 'snapshot'

*       place beeper
?       print help screen
return  run program
space   erase an object
.fi
.PP
Note: after running program, press ESC to leave screen setup as it is, or press
any other key to reset screen to setup before program execution.
.br
.SH FILES
file.k                  source program
.br
file.scr                picture of screen, without borders
.br
snapshot                picture of screen, with borders
.br
.SH SEE\ ALSO
Pattis, Richard E.; 
.ul 1
Karel the Robot
.br
.SH AUTHOR
Jan Miksovsky
.SH BUGS
Some of the "features" of this interpreter are superfluous: e.g., the
dashed lines which serve no purpose other than to make the screen look
like the pictures in the book.
